version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: exam_proctoring_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=exam_proctoring

  api:
    build: .
    container_name: face_detection_api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=exam_proctoring
      - EVENTS_COLLECTION=events
    depends_on:
      - mongodb
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data:
